version: "3"
services:
  tranql:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8001:8001"
    command: gunicorn --workers=1 --bind=0.0.0.0:8001 --name=tranql --timeout=600 --reload tranql.api:app
    environment:
      - SCHEMA_CONFIG_PATH=/home/tranql/dev-schema.yaml
    volumes:
      - ./src:/home/tranql/tranql/src
      - ./src/tranql/conf/dev-schema.yml:/home/tranql/dev-schema.yaml

  #################################################################################
  ##
  ## A memory cache for results of high volume service requests.
  ## https://redis.io/docs/stack/get-started/install/docker/
  ##
  #################################################################################
  redis:
    image: 'redis/redis-stack:6.2.4-v2'
    environment:
      - REDIS_ARGS=--requirepass $REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'