version: "3"
services:
  tranql:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8001:8001"
    command: gunicorn --workers=1 --bind=0.0.0.0:8001 --name=tranql --timeout=600 --reload tranql.api:app
    volumes:
      - ./src:/home/tranql/tranql/src
  redis_graph:
    image: redislabs/redisgraph
    volumes:
      - ./redis_data:/data